### ISSUE TITLE
Add base design for core fields

### ISSUE THREAD

**Issue by tbeck** [ocupop/ocubits#15]
@shellyrobertson  - Can you help us establish baseline design for these fields? I think that we could probably pull from the work you are doing with SNAP.

- [x] TextInput
- [x] TextArea
- [x] SelectInput
- [x] EmailInput
- [x] NumberInput
- [x] PhoneInput
- [x] Checkbox
- [x] Switch

Ideally we can work from a Figma file that is setup using the Amplify UI Kit as a starter.

**Comment by paulstroot** [comment]
All set. Used the designs provided by Shelly
