### ISSUE TITLE
Hosting and CI/CD for Storybook

### ISSUE THREAD

**Issue by tbeck** [ocupop/ocubits#39]
I would like us to consider using Chromatic: https://www.chromatic.com/ for this project.

**Comment by paulstroot** [comment]
Lots to do with the overall Ocubits devleopment. For the deployment discussion though, do we need to decide if Chromatic is the best hosting for the final product? or do we want to talk about GCP or other hosting solutions?

**Comment by paulstroot** [comment]
@tbeck , here are initial thoughts. I'll try to schedule a meet with you to discuss/

Custom Domain: Looks straightforward on the Chromatic side. We will need to decide on the domain/subdomain, and have somebody update the DNS for that domain:
https://www.chromatic.com/blog/custom-domain-for-your-storybook/

Test & Document feedback workflow: Let's discuss this. Should we use github issues? Looks like chromatic has a "Reviews" tool that I'll want to look deeper into. Maybe github for dev issues, and Chromatic for UI updates?

Branch / PR Strategy. Let's discuss further.
